[bttc]
src.github = "bttcprotocol/bttc"
fetch.github = "bttcprotocol/bttc"
git.fetchSubmodules = true

[delivery]
src.github = "bttcprotocol/delivery"
fetch.github = "bttcprotocol/delivery"
git.fetchSubmodules = true

[launch]
src.git = "https://github.com/bttcprotocol/launch.git"
#src.manual = "f71388e3a8091a1c6bc10aa03d7edf8e7b638f23"
fetch.git = "https://github.com/bttcprotocol/launch.git"

# python
[my_cookies]
src.pypi="my_cookies"
fetch.pypi="my_cookies"

[epc]
src.pypi="epc"
fetch.pypi="epc"

#emacs
[lsp-bridge]
src.git = "https://github.com/manateelazycat/lsp-bridge.git"
fetch.git = "https://github.com/manateelazycat/lsp-bridge.git"

[ligature.el]
src.git = "https://github.com/mickeynp/ligature.el.git"
fetch.git = "https://github.com/mickeynp/ligature.el.git"

[copilot.el]
src.git = "https://github.com/zerolfx/copilot.el.git"
fetch.git = "https://github.com/zerolfx/copilot.el.git"

[org-cv]
src.git = "https://gitlab.com/Titan-C/org-cv.git"
fetch.git = "https://gitlab.com/Titan-C/org-cv.git"

[Flask-SimpleLDAP]
src.pypi="Flask-SimpleLDAP"
fetch.pypi="Flask-SimpleLDAP"

#ruby
[aws-codedeploy-agent]
src.git = "https://github.com/aws/aws-codedeploy-agent.git"
fetch.git = "https://github.com/aws/aws-codedeploy-agent.git"

# python
